//
// Created by Rodrigo Asbun on 10/24/21.
//

#ifndef CPPTECHNICALINTERVIEWPREP_HACKERRANK_H
#define CPPTECHNICALINTERVIEWPREP_HACKERRANK_H

void forLoop();


#endif //CPPTECHNICALINTERVIEWPREP_HACKERRANK_H
